# query the client data
timeperiod: 300   # time in seconds
debug:
  # log file e.g. /tmp/emu.log; stderr; stdout
  # default: stderr
  file: stderr
  # flag: (default: standard)
  #       trace    >> Warning | Info | Error | Fatal | Debug | Trace
  #       debug    >> Warning | Info | Error | Fatal | Debug
  #       standard >> Warning | Info | Error | Fatal
  flag: debug
meter:
  # key >> name of device
  #   type: mbclient | mbgateway | fritz!powerline
  #   connection: connectionstring eg: TCP 192.168.65.197:502  DeviceId:1 Timeout:500 (timeout in ms (default 1000ms)
  primarymeter:
    type: mbclient
#    connection: tcp smartfox.fritz.box:502 deviceid:1 retry:2 timeout:100
    connection: tcp 192.168.65.197:502 deviceid:1 retry:3 timeout:100
    measurand:
      E: 'address:40999 uint64'
      P: 'address:41017 uint32'
  boiler:
    type: mbclient
#    connection: tcp smartfox.fritz.box:502 deviceid:1 retry:2 timeout:100
    connection: tcp 192.168.65.197:502 deviceid:1 retry:3 timeout:100
    measurand:
      E: 'address:41007 uint64'
      P: 'address:41041 uint32'
  heatpump:
    type: mbgateway
    connection: http http://raspberryz.fritz.box:8080 retry:3 timeout:500
    measurand:
      E: 'address:4124 uint32 sf:0'
      P: 'address:4116 uint32 sf:-2'
  dryer:
    type: fritz!powerline
    connection: http://fritz.box ain:116570149698 username:smarthome password:7Wl6UW5TsOr5Ba6uMbOO timeout:1500 maxretries:3
    measurand:
      E: 'command:getswitchenergy'
      P: 'command:getswitchpower sf:3'
  inverter:
    type: mbclient
#    connection: tcp fronius.fritz.box:502 deviceid:1 retry:2 timeout:200
    connection: tcp 192.168.65.196:502 deviceid:1 retry:3 timeout:1000
    measurand:
      E: 'address:40101 float32'
      P: 'address:40091 float32'

measurand:
  E:
     name: Energy
     type: delta
  P:
    name: Power
    type: snap

# webserver configuration
webserver:
  active: yes
  port: 4000
  # enable/disable webservices
  webservices:
    version: true
    currentdata: true
    data: true
    download: true
csv:
  path: C:\temp
  filenameformat: Energy_yyyymm.csv
  separator: ;
  decimalseparator: ","
  dateformat: yyyy-mm-dd HH:MM:SS
influx:
  Host: 192.168.65.41
  Port: 8086
  User: admin
  password:
  location: Wullersdorf
  database: myhome_test

