# query the client data
timeperiod: 300   # time in seconds
debug:
  # log file e.g. /tmp/emu.log; stderr; stdout
  # default: stderr
  file: stderr
  # flag: (default: standard)
  #       trace    >> Warning | Info | Error | Fatal | Debug | Trace
  #       debug    >> Warning | Info | Error | Fatal | Debug
  #       standard >> Warning | Info | Error | Fatal
  flag: debug
meter:
  # key >> name of device
  #   type: mbclient | mbgateway | fritz!powerline
  #   connection: connectionstring eg: TCP 192.168.65.197:502  DeviceId:1 Timeout:500 (timeout in ms (default 1000ms)
  primarymeter:
    type: mbclient
    #    connection: tcp smartfox.fritz.box:502 deviceid:1 maxretries:3 timeout:1000
    connection: tcp 192.168.65.197:502 deviceid:1 maxretries:3 timeout:1000
    measurand:
      E: 'address:40999 uint64'
      E_GRID: 'address:41003 uint64'
      P: 'address:41017 sint32'
  boiler:
    type: mbclient
    #    connection: tcp smartfox.fritz.box:502 deviceid:1 maxretries:3 timeout:1000
    connection: tcp 192.168.65.197:502 deviceid:1 maxretries:3 timeout:1000
    measurand:
      E: 'address:41007 uint64'
      P: 'address:41041 uint32'
  heatpump:
    type: mbgateway
    connection: http http://raspberryz.fritz.box:8080 maxretries:3 timeout:1000
    measurand:
      E: 'address:4124 uint32 sf:0'
      P: 'address:4116 uint32 sf:-2'
  dryer:
    type: fritz!powerline
    connection: http://fritz.box ain:116570149698 username:smarthome password:7Wl6UW5TsOr5Ba6uMbOO timeout:2000 maxretries:3
    measurand:
      E: 'command:getswitchenergy'
      P: 'command:getswitchpower sf:-3'
  wallbox:
    type: s0counter
    connection: http://wallbox:4000/currentdata timeout:1000 maxretries:3 cache:1000
    measurand:
      E: 'key:wallbox value:MeterReading sf:3'
      P: 'key:wallbox value:Flow sf:3'
  portablewater:
    type: s0counter
    connection: http://water:4000/currentdata timeout:1000 maxretries:3 cache:1000
    measurand:
      V: 'key:portablewater value:MeterReading sf:3'
      Q: 'key:portablewater value:Flow sf:0'
  inverter:
    type: mbclient
    #    connection: tcp fronius.fritz.box:502 deviceid:1 maxretries:3 timeout:1000
    connection: tcp 192.168.65.196:502 deviceid:1 maxretries:3 timeout:1000
    measurand:
      E: 'address:40101 float32'
      P: 'address:40091 float32'
measurand:
  E:
    Energy: 'type:delta out:influx,csv'
    Power (avg): 'type:avg out:influx,csv'
    Energy (Wh): 'type:value out:influx,csv'
  E_GRID:
    Energy to Grid: 'type:delta out:influx,csv'
    Energy to Grid (Wh): 'type:value out:influx,csv'
  P:
    Power (W): 'type:value out:csv'
  V:
    Liter: 'type:delta out:csv'
    Liter (avg): 'type:avg out:csv'
    Liter (l): 'type:value out:csv'
  Q:
    Liter (l/h): 'type:value out:csv'

# webserver configuration
webserver:
  active: yes
  port: 4000
  # enable/disable webservices
  webservices:
    version: true
    currentdata: true
    meter: true
    allmeters: true
    data: true
    download: true
csv:
  path: C:\temp
  filenameformat: Energy_yyyymm.csv
  separator: ;
  decimalseparator: ","
  dateformat: yyyy-mm-dd HH:MM:SS
influx:
  serverurl: http://192.168.65.41:8086
  User: admin
  password:
  location: Wullersdorf
  database: myhome_test
  measurement: test

